server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/xunwu?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
    mapperLocations: classpath:mapper/**/*.xml